import type { APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import { ApproveRequest } from '../../application/ApproveRequest';
import { RejectRequest } from '../../application/RejectRequest';
import { ApproverGate } from '../../application/ApproverGate';
import {
  UnknownRequestError,
  UnknownTokenError,
  TerminalRequestError,
  LockedOutError,
  AlreadyActedError,
  OtpNotValidatedError,
  PurchaseRequestDomainError,
} from '../../domain/errors';
import { makeRequestRepository } from '../../infrastructure/DynamoDbRequestRepository';
import { makeApproverRepository } from '../../infrastructure/DynamoDbApproverRepository';
import { StubEvidenceGenerator } from '../../infrastructure/StubEvidenceGenerator';

/**
 * Error → HTTP mapper for the signature endpoints (#10 approve, #11 reject),
 * following design-api policy:
 *
 *   Unknown request / unknown token      → 404
 *   Lockout                              → 403
 *   Already acted (signed/rejected dup)  → 409
 *   OTP not validated before acting      → 401 (validatedAt marker, spec R1/R2)
 *   Terminal request                     → 410
 *   Any other domain validation          → 400
 *   Anything unexpected                  → 500
 *
 * The 401 branch is LIVE: approve/reject take no code, so they require the
 * durable `validatedAt` marker written by a successful OTP validation (PR #3
 * consumes the OTP; ValidateOtp writes the marker). An approver who never
 * validated an OTP gets 401 here.
 */
function errorResponse(err: unknown): { status: number; body: Record<string, unknown> } {
  if (err instanceof UnknownRequestError || err instanceof UnknownTokenError) {
    return { status: 404, body: { error: (err as Error).name, message: (err as Error).message } };
  }
  if (err instanceof LockedOutError) {
    return { status: 403, body: { error: err.name, message: err.message } };
  }
  if (err instanceof AlreadyActedError) {
    return { status: 409, body: { error: err.name, message: err.message } };
  }
  if (err instanceof TerminalRequestError) {
    return { status: 410, body: { error: err.name, message: err.message } };
  }
  if (err instanceof OtpNotValidatedError) {
    return { status: 401, body: { error: err.name, message: err.message } };
  }
  const name = (err as Error)?.name ?? 'Error';
  const message = (err as Error)?.message ?? 'Unexpected error';
  if (err instanceof PurchaseRequestDomainError) {
    return { status: 400, body: { error: name, message } };
  }
  return { status: 500, body: { error: name, message } };
}

function json(status: number, body: unknown): APIGatewayProxyResult {
  return {
    statusCode: status,
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  };
}

function tokens(event: APIGatewayProxyEvent): { requestId: string; token: string } {
  return {
    requestId: event.pathParameters?.requestId ?? '',
    token: event.pathParameters?.token ?? '',
  };
}

export function buildApprove(approveRequest: ApproveRequest) {
  return async (event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> => {
    const { requestId, token } = tokens(event);
    try {
      const detail = await approveRequest.execute({ requestId, token });
      return json(201, detail);
    } catch (err) {
      const { status, body } = errorResponse(err);
      return json(status, body);
    }
  };
}

export function buildReject(rejectRequest: RejectRequest) {
  return async (event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> => {
    const { requestId, token } = tokens(event);
    let confirm: unknown;
    try {
      confirm = (JSON.parse(event.body ?? '{}') as Record<string, unknown>)?.confirm;
    } catch {
      return json(400, { error: 'Invalid JSON body', message: 'Body must be valid JSON' });
    }
    if (confirm !== true) {
      return json(400, {
        error: 'ValidationError',
        message: 'Reject requires { confirm: true }',
      });
    }
    try {
      const detail = await rejectRequest.execute({ requestId, token });
      return json(201, detail);
    } catch (err) {
      const { status, body } = errorResponse(err);
      return json(status, body);
    }
  };
}

/**
 * Production Lambda handlers wired to the real ports (design-api serverless.yml
 * mapping):
 *   POST /api/approvals/{requestId}/token/{token}/approve  → approve (#10)
 *   POST /api/approvals/{requestId}/token/{token}/reject   → reject  (#11, {confirm:true})
 *
 * Evidence is generated by the completion CAS winner through the
 * {@link EvidenceGeneratorPort}; PR #4 injects a stub, PR #5 replaces it with
 * the real PdfGenerator.
 */
const requests = makeRequestRepository();
const approvers = makeApproverRepository();
const gate = new ApproverGate(requests, approvers);
const evidence = new StubEvidenceGenerator();

export const approve = buildApprove(new ApproveRequest(gate, approvers, requests, evidence));
export const reject = buildReject(new RejectRequest(gate, approvers, requests));